import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ChatMessage } from "../domain/prac";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title className="bg-gray-50">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ChatMessage />
      </main>
    </div>
  );
};

export default Home;
